name: 'Release to GitHub'

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    name: Build Apps

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.x'

    - name: Restore NuGet packages
      shell: bash
      run: |
        dotnet restore .

    - name: Build solution
      shell: bash
      run: |
        dotnet build . -c Release

    - name: Create FunctionApp artifact - In-Proc App
      shell: bash
      run: |
        pushd InProcApp
        dotnet publish . -c Release -o published
        popd

    - name: Create FunctionApp artifact - Out-of-Proc App
      shell: bash
      run: |
        pushd OutOfProcApp
        dotnet publish . -c Release -o published
        popd

    - name: Upload FunctionApp artifact - In-Proc App
      uses: actions/upload-artifact@v2
      with:
        name: ip
        path: InProcApp/published

    - name: Upload FunctionApp artifact - Out-of-Proc App
      uses: actions/upload-artifact@v2
      with:
        name: oop
        path: InProcApp/published

  release:
    name: Release Apps
    needs: build

    runs-on: ubuntu-latest

    steps:
    - name: Download FunctionApp artifact - In-Proc App
      uses: actions/download-artifact@v2
      with:
        name: ip
        path: published/ip

    - name: Download FunctionApp artifact - Out-of-Proc App
      uses: actions/download-artifact@v2
      with:
        name: oop
        path: published/oop

    - name: Zip FunctionApp artifacts
      shell: bash
      run: |
        cd published/ip
        zip -qq -r ip.zip .
        cd $GITHUB_WORKSPACE

        cd published/oop
        zip -qq -r oop.zip .
        cd $GITHUB_WORKSPACE

        mv published/ip/ip.zip published/ip.zip
        mv published/oop/oop.zip published/oop.zip

    - name: Release FunctionApp artifacts to GitHub
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GH_PAT }}"
        prerelease: false
        files: |
          published/ip.zip
          published/oop.zip
